### ISSUE TITLE
Does jaxen-1.2.0 support for Java 11? If not, any timeline or recommendation?

### ISSUE THREAD

**Issue by xinmin-zhou** [jaxen-xpath/jaxen#109]
Hi Expert,
I would appreciate if you could share your knowledge related with me? Thanks.

Regards,
Xinmin

**Comment by elharo** [comment]
It should work. I haven't heard anyone report otherwise yet. If there are any issues they're probably around the Java Platform Module System.

**Comment by xinmin-zhou** [comment]
Thank you for your prompt response and much appreciated!

Regards,
Xinmin

**Comment by vaishnavi-naidu** [comment]
Is jaxen 1.2.0 compatible with Java 11? Did you get any errors or it is fine
