### ISSUE TITLE
JDK 9, 10 ,11 Support

### ISSUE THREAD

**Issue by Stexxen** [jaxen-xpath/jaxen#12]
This is primarily for JDK 11, although effects JDKs 9 and 10 as well. Although you can work around the problem in 9+10, you cannot in 11.

java.xml is a built in module with the JDK. It exports among other packages this one
```
    exports org.w3c.dom;
```

jaxen, includes the class org.w3c.dom.UserDataHandler, and with [Automatic modules](http://openjdk.java.net/projects/jigsaw/spec/sotms/#automatic-modules) this is exported as `org.w3c.dom` and then clashes with the explicit package declared in java.xml

This results in the errors similar the to following during compilation
```
Error:java: module java.xml.soap reads package org.w3c.dom from both java.xml and jaxen
Error:java: module java.xml.bind reads package org.w3c.dom from both jaxen and java.xml
Error:java: module java.xml.ws reads package org.w3c.dom from both java.xml and jaxen
```

I see 2 potential solutions

1. Add a module-info.class that explicitly defines the exported packages.
2. Remove org.w3c.dom.UserDataHandler from the jaxen source and add java.xml as a dependancy.

**Comment by elharo** [comment]
module-info.class files have problems in some Java 8 environments, such as App Engine. I prefer option 2. So far we don't have an acceptable PR implementing that though.

**Comment by Stexxen** [comment]
ahhh, I hadn't seen your response before putting together my PR which takes the Option 1 route.
