### ISSUE TITLE
how can I  report a security issue?

### ISSUE THREAD

**Issue by howchen** [jaxen-xpath/jaxen#163]
Hello, 
        how can I  report a security issue?

**Comment by elharo** [comment]
If it's a real issue you've personally discovered and can explain, feel free to drop me an email.

If it's some security tool logging a warning, that is 95% likely not to be a security issue but rather a bug in the tool. You can file that here after you have investigated if you are willing to vouch that it is a true security issue, but be aware that these tools are almost never correct when analyzing Jaxen.

**Comment by howchen** [comment]
I've emailed you the details of the problem. Please check it.

**Comment by elharo** [comment]
I don't see any email about this in my inbox yet

**Comment by elharo** [comment]
What is ***@***.***? I have no email from you in any of my accounts.

**Comment by howchen** [comment]
I'm sorry, but where can I find your email account?   I have  emailed to elharo @ ibiblio.org

**Comment by howchen** [comment]
chenhaoyy0917 @ 163.com



---- Replied Message ----
| From | Elliotte Rusty ***@***.***> |
| Date | 04/28/2023 23:09 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [jaxen-xpath/jaxen] how can I report a security issue? (Issue #163) |

No message yet. What address are you sending from?

**Comment by howchen** [comment]
I just sent you an email using another email address. Please let me know if you get it.
