### ISSUE TITLE
evaluateFirst call returns zero results for "//*" xpath query

### ISSUE THREAD

**Issue by mykola-mokhnach** [jaxen-xpath/jaxen#18]
We are using JDOM2/Jaxen combination in our project and it turns out, that `//*` xpath query returns all XML nodes if called via `XPathExpression.evaluate`, but zero results are returned if `XPathExpression.evaluateFirst` is called with the same argument. More details and CI results at: https://github.com/appium/appium-uiautomator2-server/pull/238

**Comment by elharo** [comment]
Looks like this is an issue in JDOM2. I don't think we have any `evaluateFirst` method. I suggest reporting it to JDOM. If you can reproduce using only Jaxen classes, reopen and I'll take a look.

**Comment by mykola-mokhnach** [comment]
Thanks, I'll try to report the issue to JDOM2
