### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by AlexanderBartash** [jaxen-xpath/jaxen#182]
2 clause https://github.com/jaxen-xpath/jaxen/blob/master/pom.xml#L16
3 clause https://github.com/jaxen-xpath/jaxen?tab=License-1-ov-file

**Comment by elharo** [comment]
Good catch. I think I'm going to assume the one in the actual document is correct.

**Comment by elharo** [comment]
Per wikipedia BSD License 2.0 is the 3 clause license so there's no conflict.

https://en.wikipedia.org/wiki/BSD_licenses

The 2-clause license  is the "Simplified BSD License" or "FreeBSD License".

**Comment by AlexanderBartash** [comment]
https://opensource.org/license/BSD-2-Clause
https://opensource.org/license/BSD-3-Clause

They are different :point_up:

**Comment by elharo** [comment]
Yes, they are, but the pom.xml does not claim to use the BSD-2-Clause license. It correctly says we use the BSD 2.0 license which is the BSD-3-Clause license.

**Comment by AlexanderBartash** [comment]
Well, ok, I do not mind :)

The reason why I created this ticket, I was trying to use tools for dependencies analysis to detect which licenses transitive deps require, like 

https://github.com/mikepenz/AboutLibraries
https://github.com/jaredsburrows/gradle-license-plugin
https://github.com/cashapp/licensee
https://github.com/oss-review-toolkit https://oss-review-toolkit.org/ort/

Typically they rely on something called SPDX license identifier https://spdx.org/licenses/ for BSD 3 clause it is `BSD-3-Clause` that allows it to be detected properly so that people can actually comply with it, because if you do not know you can't.

So if it was changed to SPDX identifier it would increase the chance that people will comply.

**Comment by elharo** [comment]
Jaxen predates SPDX by about a decade. If the ask is to use a SPDX identifier here instead of the plain text, I can consider that.
