### ISSUE TITLE
Create tags

### ISSUE THREAD

**Issue by wltjr** [jaxen-xpath/jaxen#4]
This seems to be the official source repo for jaxen. Can some tags be created? I see some fixes since 1.1.6, maybe can start with a new tag/release 1.1.7. Thanks!

**Comment by elharo** [comment]
It is as official a repo as we have since Codehaus shut down. There are no current plans for a new release. Is there anything critical that needs to be pushed out?

**Comment by wltjr** [comment]
Nothing critical, just would like to be able to pull from live sources. This is for the jaxen package on Gentoo. Presently pulling sources from maven.
