### ISSUE TITLE
Recursive dependency on dom4j

### ISSUE THREAD

**Issue by wltjr** [jaxen-xpath/jaxen#58]
Refiling from https://github.com/codehaus/jaxen/issues/3 on behalf of @htgoebel.

> jaxen requires dom4j for compiling. and dom4j requires jaxen for compiling.
>
> This inhibits building both packages from source (read: without basing .jars downloaded
> elsewhere). Building software from pure source is important to provide a verifiable path from
> source code to binary, see [reproducible builds](https://reproducible-builds.org/).
>
> Please remove this dependency-cycle. Thanks.

I am also running into this https://github.com/Obsidian-StudiosInc/os-xtoo/issues/71

**Comment by wltjr** [comment]
Per this comment https://github.com/dom4j/dom4j/issues/24#issuecomment-492422016 I believe the issue is more on the jaxen side than dom4j. However, I noticed for 2.x dom4j has already been split out. How far away is a 2.x release of jaxen? Maybe one can be released sooner than later to see how it effects things. Thanks!

**Comment by elharo** [comment]
Absent contributions of resources, it will happen when it happens. Changes will be required to dom4j too, I expect.

**Comment by wltjr** [comment]
@elharo sure, though I think this could be resolved if you are open to donating or moving 2 classes over to dom4j from jaxen per https://github.com/dom4j/dom4j/issues/24#issuecomment-492438627. That seems the simplest and cleanest solution.

Otherwise, each would need a separate module for the other, but I think even then you still have a bootstrap issue. Either way, I took care of it for my needs for now by moving those two classes over and making them part of dom4j instead of jaxen.

**Comment by elharo** [comment]
It's all open source. dom4j can do what they like.

That said, I don't recommend that dom4j include any packages in the org.jaxen namespace. That way lies madness and dependency conflicts. A much better approach is to provide their own navigator somewhere in the dom4j packages, if necessary by forking the existing one into a different package.

**Comment by wltjr** [comment]
You cannot build dom4j, without jaxen being built. You cannot build that portion of jaxen without dom4j. It is a circular dependency situation. The only way to break the circle is to move the code or remove the dependency. Given how much dom4j uses jaxen, or at least has lines of code needing jaxen to build. it is less feasible to drop jaxen from dom4j. dom4j portions can be split from the main jaxen as you have, but you still cannot build that without having built dom4j.

Try to build both from source without a jar of either, and you cannot. One must exist in a jar form to build the other.
