### ISSUE TITLE
PatternParser.navigationStep(step) always returns true

### ISSUE THREAD

**Issue by santhosh-tekuri** [jaxen-xpath/jaxen#7]
[PatternParser.navigationStep(step)](https://github.com/jaxen-xpath/jaxen/blob/master/src/java/main/org/jaxen/pattern/PatternParser.java#L282) always returns true

line 289: `if ( step.getClass().equals( DefaultStep.class ) )`

always returns false, because DefaultStep is abstract class.

So navigationStep(...) always returns true

i guess the implementation of navigationStep(...) is wrong. If not, we can simplify code by removing navigationStep(...) method

**Comment by elharo** [comment]
This makes sense.

I'm not sure how widely used the pattern package actually is. I don't use it, for instance; and I can't think of anyone who does. Is there someone out thee who is using this?

**Comment by elharo** [comment]
Pattern package has been deleted.
